title: DemixApps
author:
  name: Demix Apps
  email: mustafademir013@gmail.com
description: > # this means to ignore newlines
  DemixApps makes mobile games and apps.
type: freemium # Choose one from "open source", "free", freemium, ad supported, commercial
google_analytics: UA-NNNNNNNN-N
links:
  app_store: https://apps.apple.com/tr/developer/mustafa-demir/id1204716531
  google_play: https://play.google.com/store/apps/developer?id=DmX
theme: mobikit
plugins:
 - jekyll-seo-tag
